/* empty css                      */import{S as E,i as c,a as M}from"./assets/vendor-CHIICdOG.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const p=document.querySelector("#search-form"),y=document.querySelector(".gallery"),v=document.querySelector(".loader"),L=document.querySelector(".loading-message"),m=document.querySelector("#load-more"),w=document.querySelector("#loading-message-bottom"),P=new E(".gallery a");let l=1,d="",r=[],h=0;function n(o,t=!0,a="hidden"){o.classList.toggle(a,!t)}function b(){n(v,!0)}function f(){n(v,!1)}function B(){n(L,!0)}function I(){setTimeout(()=>n(L,!1),1e3)}function R(){n(w,!0)}function T(){n(w,!1)}function S(){m.classList.add("visible")}function g(){m.classList.remove("visible")}function $(){y.innerHTML=""}async function A(o,t){return(await M.get("https://pixabay.com/api/",{params:{key:"52711277-f6548e7cff1e8c2b9d8773286",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:t}})).data}function O(o){const t=Math.floor(o.length/3)*3,i=o.slice(0,t).map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <div class="info-block"><span class="info-title">Likes</span><span class="info-value">${e.likes}</span></div>
          <div class="info-block"><span class="info-title">Views</span><span class="info-value">${e.views}</span></div>
          <div class="info-block"><span class="info-title">Comments</span><span class="info-value">${e.comments}</span></div>
          <div class="info-block"><span class="info-title">Downloads</span><span class="info-value">${e.downloads}</span></div>
        </div>
      </a>
    `).join("");return y.insertAdjacentHTML("beforeend",i),P.refresh(),o.slice(t)}async function q(o){l===1&&($(),r=[]),b(),B();try{const t=await A(o,l);if(f(),I(),t.hits.length===0){c.error({message:"Sorry, no images found. Try another query!",position:"topRight",backgroundColor:"#EF4040"}),g();return}h=t.totalHits,r=r.concat(t.hits),r=O(r),r.length===0&&l*40>=h?(g(),c.info("You've reached the end of the results.")):S()}catch(t){f(),c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}}p.addEventListener("submit",o=>{o.preventDefault();const t=o.target.searchQuery.value.trim();t&&(d=t,l=1,q(d),p.reset())});m.addEventListener("click",async()=>{g(),R(),b(),await new Promise(o=>setTimeout(o,2e3)),l+=1;try{await q(d);const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}catch{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{T(),f(),S()}});
//# sourceMappingURL=index.js.map
